apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-allchannel-carrier-peer0
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: joinchannel-peer0-join-allchannel-carrier-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-channel-join
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.2.2
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.vault:8200
      authpath: localcarrier
      adminsecretprefix: secretsv2/data/carrier/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secretsv2/data/carrier/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
