apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-net-ca
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server   
  values:
    deployment:
      annotations:
    annotations:  
      service:
        - example1: example2
      pvc:
    metadata:
      namespace: supplychain-net
      images:
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
        ca: ghcr.io/hyperledger/bevel-fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: supplychain-admin
        
    storage:
      storageclassname: supplychain-bevel-storageclass
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: http://vault.vault:8200
      authpath: localsupplychain
      secretcert: secretsv2/data/supplychain/ordererOrganizations/supplychain-net/ca?ca.supplychain-net-cert.pem
      secretkey: secretsv2/data/supplychain/ordererOrganizations/supplychain-net/ca?supplychain-net-CA.key
      secretadminpass: secretsv2/data/supplychain/credentials/supplychain-net/ca/supplychain?user
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          clusteripport: 7054
    proxy:
      provider: none
      type: orderer
      external_url_suffix: develop.local.com
