apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-net-ca
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: carrier-net-ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server  
  values:
    metadata:
      namespace: carrier-net
      images:
        alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
        ca: ghcr.io/hyperledger/bevel-fabric-ca:1.4.8
    deployment:
      annotations:
    annotations:  
      service:
        - example1: example2
      pvc:
 
    server:
      name: ca
      tlsstatus: true
      admin: carrier-admin 
  
    storage:
      storageclassname: carrier-bevel-storageclass
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://vault.vault:8200
      authpath: localcarrier
      secretcert: secretsv2/data/carrier/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: secretsv2/data/carrier/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretadminpass: secretsv2/data/carrier/credentials/carrier-net/ca/carrier?user
      serviceaccountname: vault-auth
      type: hashicorp
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          clusteripport: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: develop.local.com
